{{- $fixedConfig := dict "relution" (dict "server" (dict "url" (printf "http://%s:%v" (include "relution.fullname" .) .Values.service.port))) -}}
{{- $config := mergeOverwrite (deepCopy .Values.smg.app.config) $fixedConfig -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "relution.fullname" . }}-smg-config
  labels:
    {{- include "relution.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- toYaml $config | nindent 4 }}
