ingress:
  enabled: true
  hosts:
    - host: '{{ required "relution.config.relution.server.externalURL is required!" .Values.relution.config.relution.server.externalURL | replace "https://" "" }}'
      paths:
        - path: /
          pathType: ImplementationSpecific

relution:
  config:
    relution:
      server:
        externalURL: https://test.relution.io
      database:
        type: mariadb
        url: jdbc:mariadb://mariadb:3306/relution
        username: relution
        password: relution

mariadb:
  enabled: true
  fullnameOverride: mariadb
  auth:
    rootPassword: relution
    username: relution
    password: relution
    database: relution

heapDumpExporter:
  enabled: true
  persistence:
    enabled: false
  s3:
    bucket: s3://test-relution-io
    awsAccessKeyId: relution
    awsSecretAccessKey: relution
