{{- if .Values.imageMagick.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "relution.fullname" . }}-imagemagick
  labels:
    {{- include "relution.labels" . | nindent 4 }}
data:
  security-policy.xml: |
    {{- tpl (.Files.Get "config/imagemagick-security-policy.xml") $ | nindent 4 }}
{{- end }}
