{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "relution.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "relution.labels" . | nindent 4 }}
spec:
  entryPoints: {{ toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    {{- with .Values.ingressRoute.defaultRoute }}
    {{- if .enabled }}
    - kind: Rule
      match: "Host(`{{ tpl .host $ }}`)"
      {{- with .middlewares }}
      middlewares:
      {{- range . }}
      - name: {{ .name }}
        namespace: {{ .namespace }}
      {{- end }}
      {{- end }}
      services:
      - kind: Service
        name: {{ $fullName }}
        namespace: {{ $.Release.Namespace }}
        port: {{ $svcPort }}
    {{- end }}
    {{- end }}
    {{- range .Values.ingressRoute.additionalRoutes }}
    - kind: {{ .kind }}
      match: "{{ tpl .match $ }}"
      {{- with .middlewares }}
      middlewares:
      {{- range . }}
      - name: {{ .name }}
        namespace: {{ .namespace }}
      {{- end }}
      {{- end }}
      services:
      - kind: Service
        name: {{ $fullName }}
        namespace: {{ $.Release.Namespace }}
        port: {{ $svcPort }}
    {{- end }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    secretName: {{ required "ingressRoute.tls.secretName is required!" .secretName }}
    certResolver: {{ required "ingressRoute.tls.certResolver is required!" .certResolver }}
    domains: {{ toYaml .domains | nindent 6 }}
  {{- end }}
{{- end }}
