{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "relution.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "relution.labels" . | nindent 4 }}
spec:
  entryPoints: {{ toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    {{- with .Values.ingressRoute.defaultRoute }}
    {{- if .enabled }}
    - kind: Rule
      {{- if .match }}
      match: {{ tpl .match $ | quote }}
      {{- else }}
      match: "Host(`{{ tpl .host $ }}`)"
      {{- end}}
      {{- with .middlewares }}
      middlewares:
      {{- range . }}
        - name: {{ required "ingressRoute.defaultRoute.middlewares[*].name is required!" .name }}
          namespace: {{ required "ingressRoute.defaultRoute.middlewares[*].namespace is required!" .namespace }}
      {{- end }}
      {{- end }}
      services:
        - kind: Service
          name: {{ $fullName }}
          namespace: {{ $.Release.Namespace }}
          port: {{ $svcPort }}
    {{- end }}
    {{- end }}
    {{- range .Values.ingressRoute.additionalRoutes }}
    - kind: {{ required "ingressRoute.additionalRoutes[*].kind is required!" .kind }}
      match: "{{ tpl .match $ }}"
      {{- with .middlewares }}
      middlewares:
      {{- range . }}
        - name: {{ required "ingressRoute.additionalRoutes[*].middlewares[*].name is required!" .name }}
          namespace: {{ required "ingressRoute.additionalRoutes[*].middlewares[*].namespace is required!" .namespace }}
      {{- end }}
      {{- end }}
      services:
        - kind: Service
          name: {{ $fullName }}
          namespace: {{ $.Release.Namespace }}
          port: {{ $svcPort }}
    {{- end }}
  {{- with .Values.ingressRoute.tls }}
  {{- if .enabled }}
  tls:
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
    {{- if .certResolver }}
    certResolver: {{ .certResolver }}
    {{- end }}
    domains:
    {{- range .domains }}
      - main: {{ required "ingressRoute.tls.domains[*].main is required!" .main }}
        {{- with .sans }}
        sans: {{ toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
