{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "relution.fullname" . }}
  labels:
    {{- include "relution.labels" . | nindent 4 }}
spec:
  {{- .Values.networkPolicy.spec | toYaml | nindent 2 -}}
{{- end -}}
